# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/taehong/Downloads/PROG Github/PROG1700_SourceCode/w0445964_MinT/Tech Checks/TC7/TaxCalculator.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(532, 440)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.labelWeeklySalaryText = QtWidgets.QLabel(self.centralwidget)
        self.labelWeeklySalaryText.setGeometry(QtCore.QRect(20, 40, 221, 21))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.labelWeeklySalaryText.setFont(font)
        self.labelWeeklySalaryText.setObjectName("labelWeeklySalaryText")
        self.labelHowManyDependentsText = QtWidgets.QLabel(self.centralwidget)
        self.labelHowManyDependentsText.setGeometry(QtCore.QRect(20, 110, 291, 21))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.labelHowManyDependentsText.setFont(font)
        self.labelHowManyDependentsText.setObjectName("labelHowManyDependentsText")
        self.lineEditInputdependents = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditInputdependents.setGeometry(QtCore.QRect(330, 110, 113, 21))
        self.lineEditInputdependents.setText("")
        self.lineEditInputdependents.setObjectName("lineEditInputdependents")
        self.lineEditInputSalary = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditInputSalary.setGeometry(QtCore.QRect(330, 40, 181, 21))
        self.lineEditInputSalary.setText("")
        self.lineEditInputSalary.setObjectName("lineEditInputSalary")
        self.pushButtonCalculateTax = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonCalculateTax.setGeometry(QtCore.QRect(150, 171, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.pushButtonCalculateTax.setFont(font)
        self.pushButtonCalculateTax.setObjectName("pushButtonCalculateTax")
        self.labelProvinceTax = QtWidgets.QLabel(self.centralwidget)
        self.labelProvinceTax.setGeometry(QtCore.QRect(20, 230, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.labelProvinceTax.setFont(font)
        self.labelProvinceTax.setObjectName("labelProvinceTax")
        self.labelFederalTax = QtWidgets.QLabel(self.centralwidget)
        self.labelFederalTax.setGeometry(QtCore.QRect(20, 260, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.labelFederalTax.setFont(font)
        self.labelFederalTax.setObjectName("labelFederalTax")
        self.labelDedction = QtWidgets.QLabel(self.centralwidget)
        self.labelDedction.setGeometry(QtCore.QRect(20, 290, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.labelDedction.setFont(font)
        self.labelDedction.setObjectName("labelDedction")
        self.labelTotalTakeHomePay = QtWidgets.QLabel(self.centralwidget)
        self.labelTotalTakeHomePay.setGeometry(QtCore.QRect(20, 350, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.labelTotalTakeHomePay.setFont(font)
        self.labelTotalTakeHomePay.setObjectName("labelTotalTakeHomePay")
        self.labelTotalWithheld = QtWidgets.QLabel(self.centralwidget)
        self.labelTotalWithheld.setGeometry(QtCore.QRect(20, 320, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.labelTotalWithheld.setFont(font)
        self.labelTotalWithheld.setObjectName("labelTotalWithheld")
        self.labelDependentsDisplay = QtWidgets.QLabel(self.centralwidget)
        self.labelDependentsDisplay.setGeometry(QtCore.QRect(220, 296, 21, 20))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.labelDependentsDisplay.setFont(font)
        self.labelDependentsDisplay.setText("")
        self.labelDependentsDisplay.setObjectName("labelDependentsDisplay")
        self.labelDependents = QtWidgets.QLabel(self.centralwidget)
        self.labelDependents.setGeometry(QtCore.QRect(235, 297, 101, 16))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.labelDependents.setFont(font)
        self.labelDependents.setObjectName("labelDependents")
        self.labelProvincialTaxDisplay = QtWidgets.QLabel(self.centralwidget)
        self.labelProvincialTaxDisplay.setGeometry(QtCore.QRect(210, 230, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.labelProvincialTaxDisplay.setFont(font)
        self.labelProvincialTaxDisplay.setText("")
        self.labelProvincialTaxDisplay.setObjectName("labelProvincialTaxDisplay")
        self.labelFederalTaxDisplay = QtWidgets.QLabel(self.centralwidget)
        self.labelFederalTaxDisplay.setGeometry(QtCore.QRect(190, 260, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.labelFederalTaxDisplay.setFont(font)
        self.labelFederalTaxDisplay.setText("")
        self.labelFederalTaxDisplay.setObjectName("labelFederalTaxDisplay")
        self.labelDeductionDisplay = QtWidgets.QLabel(self.centralwidget)
        self.labelDeductionDisplay.setGeometry(QtCore.QRect(338, 291, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.labelDeductionDisplay.setFont(font)
        self.labelDeductionDisplay.setText("")
        self.labelDeductionDisplay.setObjectName("labelDeductionDisplay")
        self.labelTotalWithheldDisplay = QtWidgets.QLabel(self.centralwidget)
        self.labelTotalWithheldDisplay.setGeometry(QtCore.QRect(141, 320, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.labelTotalWithheldDisplay.setFont(font)
        self.labelTotalWithheldDisplay.setText("")
        self.labelTotalWithheldDisplay.setObjectName("labelTotalWithheldDisplay")
        self.labelTakeHomePayDisplay = QtWidgets.QLabel(self.centralwidget)
        self.labelTakeHomePayDisplay.setGeometry(QtCore.QRect(195, 352, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.labelTakeHomePayDisplay.setFont(font)
        self.labelTakeHomePayDisplay.setText("")
        self.labelTakeHomePayDisplay.setObjectName("labelTakeHomePayDisplay")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 532, 24))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Tax Calculator"))
        self.labelWeeklySalaryText.setText(_translate("MainWindow", "What is your weekly salary?"))
        self.labelHowManyDependentsText.setText(_translate("MainWindow", "How many dependents do you have?"))
        self.pushButtonCalculateTax.setText(_translate("MainWindow", "Calculate Tax"))
        self.labelProvinceTax.setText(_translate("MainWindow", "Provincial Tax Withheld: "))
        self.labelFederalTax.setText(_translate("MainWindow", "Federal Tax Withheld:"))
        self.labelDedction.setText(_translate("MainWindow", "Dependent Deduction for"))
        self.labelTotalTakeHomePay.setText(_translate("MainWindow", "Total Take-Home Pay:"))
        self.labelTotalWithheld.setText(_translate("MainWindow", "Total Withheld:"))
        self.labelDependents.setText(_translate("MainWindow", "dependetns:"))

