# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\PROG_SourceCode\GeoffRepo-PROG\Demos\ColorsDemo_PRG\ColorDemo.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 326)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBoxColors = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBoxColors.setGeometry(QtCore.QRect(50, 40, 281, 201))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.groupBoxColors.setFont(font)
        self.groupBoxColors.setObjectName("groupBoxColors")
        self.radioRed = QtWidgets.QRadioButton(self.groupBoxColors)
        self.radioRed.setGeometry(QtCore.QRect(60, 40, 82, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.radioRed.setFont(font)
        self.radioRed.setObjectName("radioRed")
        self.radioBlue = QtWidgets.QRadioButton(self.groupBoxColors)
        self.radioBlue.setGeometry(QtCore.QRect(60, 80, 82, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.radioBlue.setFont(font)
        self.radioBlue.setObjectName("radioBlue")
        self.radioGreen = QtWidgets.QRadioButton(self.groupBoxColors)
        self.radioGreen.setGeometry(QtCore.QRect(60, 120, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.radioGreen.setFont(font)
        self.radioGreen.setObjectName("radioGreen")
        self.lineEditMessage = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditMessage.setGeometry(QtCore.QRect(510, 40, 221, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.lineEditMessage.setFont(font)
        self.lineEditMessage.setObjectName("lineEditMessage")
        self.pushButtonDisplay = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonDisplay.setGeometry(QtCore.QRect(410, 120, 261, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButtonDisplay.setFont(font)
        self.pushButtonDisplay.setObjectName("pushButtonDisplay")
        self.labelMessage = QtWidgets.QLabel(self.centralwidget)
        self.labelMessage.setGeometry(QtCore.QRect(510, 180, 251, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.labelMessage.setFont(font)
        self.labelMessage.setText("")
        self.labelMessage.setObjectName("labelMessage")
        self.labelMessageTitle = QtWidgets.QLabel(self.centralwidget)
        self.labelMessageTitle.setGeometry(QtCore.QRect(360, 40, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.labelMessageTitle.setFont(font)
        self.labelMessageTitle.setObjectName("labelMessageTitle")
        self.labelMessageTitle2 = QtWidgets.QLabel(self.centralwidget)
        self.labelMessageTitle2.setGeometry(QtCore.QRect(360, 170, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.labelMessageTitle2.setFont(font)
        self.labelMessageTitle2.setObjectName("labelMessageTitle2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionExit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Geoff\'s Color Picker"))
        self.groupBoxColors.setTitle(_translate("MainWindow", "Colors Picker"))
        self.radioRed.setText(_translate("MainWindow", "Red"))
        self.radioBlue.setText(_translate("MainWindow", "Blue"))
        self.radioGreen.setText(_translate("MainWindow", "Green"))
        self.pushButtonDisplay.setText(_translate("MainWindow", "Display Message"))
        self.labelMessageTitle.setText(_translate("MainWindow", "Enter Text:"))
        self.labelMessageTitle2.setText(_translate("MainWindow", "Your Text:"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))

