# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/taehong/Downloads/PROG Github/PROG1700_SourceCode/w0445964_MinT/GUI/ColorPicker/ColorPicker.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButtonDisplay = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonDisplay.setGeometry(QtCore.QRect(200, 150, 211, 51))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.pushButtonDisplay.setFont(font)
        self.pushButtonDisplay.setObjectName("pushButtonDisplay")
        self.groupBoxColors = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBoxColors.setGeometry(QtCore.QRect(20, 100, 171, 141))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.groupBoxColors.setFont(font)
        self.groupBoxColors.setObjectName("groupBoxColors")
        self.radioBlue = QtWidgets.QRadioButton(self.groupBoxColors)
        self.radioBlue.setGeometry(QtCore.QRect(10, 40, 100, 20))
        self.radioBlue.setObjectName("radioBlue")
        self.radioRed = QtWidgets.QRadioButton(self.groupBoxColors)
        self.radioRed.setGeometry(QtCore.QRect(10, 70, 100, 20))
        self.radioRed.setObjectName("radioRed")
        self.radioGreen = QtWidgets.QRadioButton(self.groupBoxColors)
        self.radioGreen.setGeometry(QtCore.QRect(10, 100, 100, 20))
        self.radioGreen.setObjectName("radioGreen")
        self.labelMessage = QtWidgets.QLabel(self.centralwidget)
        self.labelMessage.setGeometry(QtCore.QRect(190, 90, 131, 61))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.labelMessage.setFont(font)
        self.labelMessage.setObjectName("labelMessage")
        self.labelYourText = QtWidgets.QLabel(self.centralwidget)
        self.labelYourText.setGeometry(QtCore.QRect(200, 210, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.labelYourText.setFont(font)
        self.labelYourText.setObjectName("labelYourText")
        self.lineEditMessage = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditMessage.setGeometry(QtCore.QRect(310, 110, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.lineEditMessage.setFont(font)
        self.lineEditMessage.setObjectName("lineEditMessage")
        self.labelDisplayMessage = QtWidgets.QLabel(self.centralwidget)
        self.labelDisplayMessage.setGeometry(QtCore.QRect(310, 220, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.labelDisplayMessage.setFont(font)
        self.labelDisplayMessage.setText("")
        self.labelDisplayMessage.setObjectName("labelDisplayMessage")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 24))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButtonDisplay.setText(_translate("MainWindow", "Display Message"))
        self.groupBoxColors.setTitle(_translate("MainWindow", "Colors Picker"))
        self.radioBlue.setText(_translate("MainWindow", "Blue"))
        self.radioRed.setText(_translate("MainWindow", "Red"))
        self.radioGreen.setText(_translate("MainWindow", "Green"))
        self.labelMessage.setText(_translate("MainWindow", "Enter Text:"))
        self.labelYourText.setText(_translate("MainWindow", "Your text:"))
